require 'browser/compatibility/dom/element/matches'
require 'browser/compatibility/dom/element/css'
require 'browser/compatibility/dom/element/offset'
require 'browser/compatibility/dom/element/style'
require 'browser/compatibility/dom/document/window'
require 'browser/compatibility/dom/mutation_observer'
