name: ubuntu

on: push
# on:
#   push:
#     branches:
#       - master
#       - "*-stable"
#       - "*ci-check"
#   pull_request:
#     branches:
#       - master

jobs:
  build:
    strategy:
      matrix:
        os: [ 'ubuntu-18.04' ]
        ruby: [ 2.6 ]
        opal: [ 1.0.3 ]

    runs-on: ${{ matrix.os }}

    env:
      OPAL_VERSION: ${{ matrix.opal }}

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup project
        run: env & bin/setup
      - name: Run test
        run: bin/rake webdrivers:chromedriver:update[87.0.4280.88] default
