# browser/event/all: Load support for all events

require 'browser/event/focus'
require 'browser/event/wheel'
require 'browser/event/data_transfer'
require 'browser/event/composition'
require 'browser/event/animation'
require 'browser/event/audio_processing'
require 'browser/event/before_unload'
require 'browser/event/composition'
require 'browser/event/clipboard'
require 'browser/event/device_light'
require 'browser/event/device_motion'
require 'browser/event/device_orientation'
require 'browser/event/device_proximity'
require 'browser/event/drag'
require 'browser/event/gamepad'
require 'browser/event/hash_change'
require 'browser/event/progress'
require 'browser/event/page_transition'
require 'browser/event/pop_state'
require 'browser/event/storage'
require 'browser/event/touch'
require 'browser/event/sensor'
require 'browser/event/message'
require 'browser/event/close'
